#pragma once

#include "protocol/TypedFrame.h"

namespace csm {

enum ControlAckStatus : uint8_t {
  ControlAckRejected = 0,
  ControlAckAccepted = 1,
};

enum ControlAckReason : uint8_t {
  ControlReasonOk = 0,
  ControlReasonBadLength = 1,
  ControlReasonBadBus = 2,
  ControlReasonUnsupportedFrame = 3,
  ControlReasonDlcOutOfRange = 4,
  ControlReasonIdNotAllowed = 5,
  ControlReasonCanNotReady = 6,
  ControlReasonCanWriteFailed = 7,
  ControlReasonBadProtocol = 8,
  ControlReasonNotArmed = 9,
  ControlReasonHostTimeout = 10,
  ControlReasonControlLeaseExpired = 11,
  ControlReasonSafetyLockout = 12,
  ControlReasonEstopAsserted = 13,
  ControlReasonFieldPowerLost = 14,
  ControlReasonEncoderFault = 15,
  ControlReasonQueueFull = 16,
  ControlReasonTxBusy = 17,
  ControlReasonBusOff = 18,
  ControlReasonErrorPassive = 19,
  ControlReasonRoleUnresolved = 20,
  ControlReasonPolicyHashMismatch = 21,
  ControlReasonNeutralProfileMissing = 22,
  ControlReasonRateLimited = 23,
  ControlReasonUnsupportedCommand = 24,
};

static constexpr uint8_t kNoFixedControlBus = 0xFF;
static constexpr uint32_t kHostCanTxAllowedPrimaryId = 0x503;
static constexpr uint32_t kHostCanTxAllowedRangeStart = 0x510;
static constexpr uint32_t kHostCanTxAllowedRangeEnd = 0x513;
static constexpr uint16_t kHostCanTxRequestPayloadLen = 19;
static constexpr uint16_t kCanRawPayloadLen = 30;
static constexpr uint8_t kCanRawMonoUsOffset = 0;
static constexpr uint8_t kCanRawIdFlagsOffset = 8;
static constexpr uint8_t kCanRawDlcFlagsOffset = 12;
static constexpr uint8_t kCanRawBusOffset = 13;
static constexpr uint8_t kCanRawDataOffset = 14;
static constexpr uint16_t kCanRxSegmentHeaderLen = 32;
static constexpr uint16_t kCanRxSegmentEntryLen = 30;
static constexpr uint8_t kCanRxSegmentMaxFrames = 15;
static constexpr uint8_t kCanRxSegmentSequenceOffset = 0;
static constexpr uint8_t kCanRxSegmentFirstCaptureOffset = 8;
static constexpr uint8_t kCanRxSegmentFrameCountOffset = 16;
static constexpr uint8_t kCanRxSegmentEntrySizeOffset = 18;
static constexpr uint8_t kCanRxSegmentEntriesOffset = 32;
static constexpr uint8_t kCanRxSegmentEntryCaptureOffset = 0;
static constexpr uint8_t kCanRxSegmentEntryMonoUsOffset = 8;
static constexpr uint8_t kCanRxSegmentEntryIdFlagsOffset = 16;
static constexpr uint8_t kCanRxSegmentEntryDlcFlagsOffset = 20;
static constexpr uint8_t kCanRxSegmentEntryBusOffset = 21;
static constexpr uint8_t kCanRxSegmentEntryDataOffset = 22;
static constexpr uint16_t kStreamSessionPayloadLen = 32;
static constexpr uint8_t kStreamSessionSchema = 1;
static constexpr uint8_t kStreamSessionReasonOffset = 1;
static constexpr uint8_t kStreamSessionFlagsOffset = 2;
static constexpr uint8_t kStreamSessionProtocolVersionOffset = 4;
static constexpr uint8_t kStreamSessionBootIdOffset = 8;
static constexpr uint8_t kStreamSessionPublishSeqOffset = 16;
static constexpr uint8_t kStreamSessionMonoUsOffset = 24;
static constexpr uint16_t kControlAckPayloadLen = 28;
static constexpr uint8_t kControlAckMonoUsOffset = 0;
static constexpr uint8_t kControlAckCommandIdOffset = 8;
static constexpr uint8_t kControlAckStatusOffset = 12;
static constexpr uint8_t kControlAckReasonOffset = 13;
static constexpr uint8_t kControlAckBusOffset = 14;
static constexpr uint8_t kControlAckDlcOffset = 15;
static constexpr uint8_t kControlAckCanIdFlagsOffset = 16;
static constexpr uint8_t kControlAckCounterOffset = 20;
static constexpr uint8_t kControlAckRejectedTotalOffset = 24;
static constexpr uint16_t kBoardEventPayloadLen = 16;
static constexpr uint8_t kBoardEventMonoUsOffset = 0;
static constexpr uint8_t kBoardEventCodeOffset = 8;
static constexpr uint8_t kBoardEventDetailOffset = 10;
static constexpr uint8_t kBoardEventCounterOffset = 12;
static constexpr uint16_t kBoardEventBootCode = 1;
static constexpr uint16_t kBoardEventCanBeginFailedCode = 2;
static constexpr uint16_t kBoardEventCanRxQueueDropCode = 3;
static constexpr uint16_t kBoardEventEncoderFaultAssertedCode = 4;
static constexpr uint16_t kBoardEventFieldPowerLostCode = 5;
static constexpr uint16_t kBoardEventEstopAssertedCode = 6;
static constexpr uint16_t kBoardEventEncoderIndexCode = 7;
static constexpr uint16_t kBoardEventEncoderWrapCode = 8;
static constexpr uint16_t kBoardEventMcp2515ErrorCode = 9;
static constexpr uint16_t kBoardEventMcp2515SpiSnapshotCode = 10;
static constexpr uint16_t kBoardEventBuiltinCanBeginFailedCode = 11;
static constexpr uint16_t kBoardEventBuiltinCanTxFailedCode = 12;
static constexpr uint16_t kBoardEventHostFrameCrcFailedCode = 13;
static constexpr uint16_t kBoardEventHostCanTxRejectedCode = 14;
static constexpr uint16_t kBoardEventHostCanTxAcceptedCode = 15;
static constexpr uint16_t kBoardEventCan0BackendUnavailableCode = 16;
static constexpr uint16_t kBoardEventMcp2515TxFailedCode = 17;
static constexpr uint16_t kBoardEventSafetyStateChangedCode = 18;
static constexpr uint16_t kBoardEventHostHeartbeatCode = 19;
static constexpr uint16_t kBoardEventHostControlSessionCode = 20;
static constexpr uint16_t kBoardEventHostCommandUnsupportedCode = 21;
static constexpr uint16_t kBoardEventFaultLockoutClearedCode = 22;
static constexpr uint16_t kBoardEventFirmwareIdentityCode = 23;
static constexpr uint16_t kBoardEventSerialTxBackpressureCode = 24;
static constexpr uint16_t kBoardEventSerialTxRingClearCode = 25;
static constexpr uint16_t kBoardEventCanRxSegmentEnqueueFailedCode = 26;
static constexpr uint16_t kBoardEventUsbCdcSessionOpenCode = 27;
static constexpr uint16_t kBoardEventUsbCdcSessionCloseCode = 28;
static constexpr uint16_t kBoardEventUsbCdcDtrChangeCode = 29;
static constexpr uint16_t kBoardEventUsbHostAbsentCanDiscardSummaryCode = 30;
static constexpr uint16_t kBoardEventMcpPassiveModeReadbackCode = 31;
static constexpr uint16_t kBoardEventMcpPassiveModeViolationCode = 32;
static constexpr uint16_t kBoardEventMcpTxreqViolationCode = 33;
static constexpr uint16_t kBoardEventTransceiverSafeStateChangedCode = 34;
static constexpr uint16_t kBoardEventUsbPowerOrResetSuspectedCode = 35;
static constexpr uint16_t kBoardEventCanFrontendPresessionHoldCode = 36;
static constexpr uint16_t kBoardEventCanFrontendSessionReadyCode = 37;
static constexpr uint16_t kBoardEventCanFrontendSessionInitFailedCode = 38;
static constexpr uint16_t kBoardEventCanFrontendFaultHoldCode = 39;
static constexpr uint16_t kBoardEventWifiTxBackpressureCode = 40;
static constexpr uint16_t kBoardEventRuntimeBreadcrumbRecoveredCode = 41;
static constexpr uint16_t kBoardHealthPayloadLen = 52;
static constexpr uint16_t kBoardHealthV1PayloadLen = 52;
static constexpr uint16_t kBoardHealthV2PayloadLen = 128;
static constexpr uint16_t kBoardHealthV4PayloadLen = 192;
static constexpr uint16_t kBoardHealthV5PayloadLen = 224;
static constexpr uint16_t kBoardHealthV6PayloadLen = 260;
static constexpr uint16_t kBoardHealthV7PayloadLen = 296;
static constexpr uint16_t kBoardHealthV8PayloadLen = 360;
static constexpr uint16_t kBoardHealthV9PayloadLen = 384;
static constexpr uint16_t kBoardHealthV10PayloadLen = 392;
static constexpr uint16_t kBoardHealthV11PayloadLen = 408;
static constexpr uint8_t kBoardHealthMonoUsOffset = 0;
static constexpr uint8_t kBoardHealthCanRxTotalOffset = 8;
static constexpr uint8_t kBoardHealthCanDropTotalOffset = 12;
static constexpr uint8_t kBoardHealthFifoOverflowTotalOffset = 16;
static constexpr uint8_t kBoardHealthTxRecordsTotalOffset = 20;
static constexpr uint8_t kBoardHealthQueueDepthOffset = 24;
static constexpr uint8_t kBoardHealthEncoderFaultTotalOffset = 28;
static constexpr uint8_t kBoardHealthTimerOkOffset = 46;
static constexpr uint8_t kBoardHealthBaseFaultBitsOffset = 48;
static constexpr uint8_t kBoardHealthVersionOffset = 52;
static constexpr uint8_t kBoardHealthSafetyStateOffset = 54;
static constexpr uint8_t kBoardHealthSafetyFaultBitsOffset = 55;
static constexpr uint8_t kBoardHealthHeartbeatAgeMsOffset = 56;
static constexpr uint8_t kBoardHealthLeaseRemainingMsOffset = 60;
static constexpr uint8_t kBoardHealthHostCrcFailOffset = 64;
static constexpr uint8_t kBoardHealthHostCanTxRequestOffset = 68;
static constexpr uint8_t kBoardHealthHostCanTxAcceptedOffset = 72;
static constexpr uint8_t kBoardHealthHostCanTxRejectedOffset = 76;
static constexpr uint8_t kBoardHealthMcpTxSuccessOffset = 80;
static constexpr uint8_t kBoardHealthMcpTxFailOffset = 84;
static constexpr uint8_t kBoardHealthBuiltinTxSuccessOffset = 88;
static constexpr uint8_t kBoardHealthBuiltinTxFailOffset = 92;
static constexpr uint8_t kBoardHealthMcpSpiErrorOffset = 96;
static constexpr uint8_t kBoardHealthMcpErrorFlagOffset = 100;
static constexpr uint8_t kBoardHealthMcpLastCanintfOffset = 104;
static constexpr uint8_t kBoardHealthMcpLastEflgOffset = 105;
static constexpr uint8_t kBoardHealthMcpLastCanctrlOffset = 106;
static constexpr uint8_t kBoardHealthMcpLastIntLowOffset = 107;
static constexpr uint8_t kBoardHealthCanRxQueueDepthOffset = 108;
static constexpr uint8_t kBoardHealthSafetyTransitionOffset = 112;
static constexpr uint8_t kBoardHealthBackendFlagsOffset = 116;
static constexpr uint8_t kBoardHealthHostHeartbeatOffset = 120;
static constexpr uint8_t kBoardHealthHostControlSessionOffset = 124;
static constexpr uint8_t kBoardHealthBus0RxOffset = 128;
static constexpr uint8_t kBoardHealthBus0DropOffset = 132;
static constexpr uint8_t kBoardHealthBus0QueueOffset = 136;
static constexpr uint8_t kBoardHealthBus0HighWaterOffset = 140;
static constexpr uint8_t kBoardHealthBus1RxOffset = 144;
static constexpr uint8_t kBoardHealthBus1DropOffset = 148;
static constexpr uint8_t kBoardHealthBus1QueueOffset = 152;
static constexpr uint8_t kBoardHealthBus1HighWaterOffset = 156;
static constexpr uint8_t kBoardHealthSerialEnqueueFailOffset = 160;
static constexpr uint8_t kBoardHealthSerialRingClearOffset = 164;
static constexpr uint8_t kBoardHealthSerialRingClearedBytesOffset = 168;
static constexpr uint8_t kBoardHealthSerialBackpressureOffset = 172;
static constexpr uint8_t kBoardHealthUplinkHighWaterOffset = 176;
static constexpr uint8_t kBoardHealthCanQueueHighWaterOffset = 180;
static constexpr uint8_t kBoardHealthMcpDrainBudgetHitOffset = 184;
static constexpr uint8_t kBoardHealthCanSegmentEnqueueFailOffset = 188;
static constexpr uint8_t kBoardHealthPoolLargeUsedOffset = 192;
static constexpr uint8_t kBoardHealthPoolLargeCapacityOffset = 196;
static constexpr uint8_t kBoardHealthPoolLargeCanReserveUsedOffset = 200;
static constexpr uint8_t kBoardHealthCanTruthQueueHighWaterOffset = 204;
static constexpr uint8_t kBoardHealthPoolAllocFailOffset = 208;
static constexpr uint8_t kBoardHealthCanTruthPoolAllocFailOffset = 212;
static constexpr uint8_t kBoardHealthDescriptorHighWaterOffset = 216;
static constexpr uint8_t kBoardHealthDiagnosticSuppressedOffset = 220;
static constexpr uint8_t kBoardHealthFirmwareProfileOffset = 224;
static constexpr uint8_t kBoardHealthVehicleImpactOffset = 228;
static constexpr uint8_t kBoardHealthCanRxTaskMaxUsOffset = 232;
static constexpr uint8_t kBoardHealthUplinkPoolHighWaterOffset = 236;
static constexpr uint8_t kBoardHealthUplinkDescriptorHighWaterOffset = 240;
static constexpr uint8_t kBoardHealthUsbReconnectOffset = 244;
static constexpr uint8_t kBoardHealthUsbForcedResetOffset = 248;
static constexpr uint8_t kBoardHealthPassiveViolationOffset = 252;
static constexpr uint16_t kBoardHealthCaptureInvalidReasonOffset = 256;
static constexpr uint16_t kBoardHealthHostAbsentBus0DiscardOffset = 260;
static constexpr uint16_t kBoardHealthHostAbsentBus1DiscardOffset = 264;
static constexpr uint16_t kBoardHealthHostAbsentFifoOverflowOffset = 268;
static constexpr uint16_t kBoardHealthHostAbsentMcpErrorOffset = 272;
static constexpr uint16_t kBoardHealthHostAbsentDurationMsOffset = 276;
static constexpr uint16_t kBoardHealthPassiveReadbackOffset = 280;
static constexpr uint16_t kBoardHealthPassiveReadbackViolationOffset = 284;
static constexpr uint16_t kBoardHealthTxreqViolationOffset = 288;
static constexpr uint16_t kBoardHealthUsbDtrChangeOffset = 292;
static constexpr uint16_t kBoardHealthPublishNextOffset = 296;
static constexpr uint16_t kBoardHealthBootSessionOffset = 304;
static constexpr uint16_t kBoardHealthUsbEpochOffset = 312;
static constexpr uint16_t kBoardHealthUsbHighWaterOffset = 316;
static constexpr uint16_t kBoardHealthUsbOverflowOffset = 320;
static constexpr uint16_t kBoardHealthUsbSentOffset = 324;
static constexpr uint16_t kBoardHealthWifiEpochOffset = 328;
static constexpr uint16_t kBoardHealthWifiHighWaterOffset = 332;
static constexpr uint16_t kBoardHealthWifiOverflowOffset = 336;
static constexpr uint16_t kBoardHealthWifiSentOffset = 340;
static constexpr uint16_t kBoardHealthWifiConnectOffset = 344;
static constexpr uint16_t kBoardHealthWifiDisconnectOffset = 348;
static constexpr uint16_t kBoardHealthWifiStallCloseOffset = 352;
static constexpr uint16_t kBoardHealthNoSinkDropOffset = 356;
static constexpr uint16_t kBoardHealthWifiSocketErrorOffset = 360;
static constexpr uint16_t kBoardHealthWifiSendBudgetOverrunOffset = 364;
static constexpr uint16_t kBoardHealthWifiSendCallMaxUsOffset = 368;
static constexpr uint16_t kBoardHealthWifiRecvCallMaxUsOffset = 372;
static constexpr uint16_t kBoardHealthWifiCloseCallMaxUsOffset = 376;
static constexpr uint16_t kBoardHealthMainLoopMaxGapUsOffset = 380;
static constexpr uint16_t kBoardHealthResetCauseBitsOffset = 384;
static constexpr uint16_t kBoardHealthResetStatusRawOffset = 388;
static constexpr uint16_t kBoardHealthPreviousBreadcrumbValidOffset = 392;
static constexpr uint16_t kBoardHealthPreviousBreadcrumbStageOffset = 396;
static constexpr uint16_t kBoardHealthPreviousBreadcrumbUptimeMsOffset = 400;
static constexpr uint16_t kBoardHealthPreviousBreadcrumbSequenceOffset = 404;
static constexpr uint32_t kResetCausePowerOn = 0x00000001;
static constexpr uint32_t kResetCauseBrownout = 0x00000002;
static constexpr uint32_t kResetCausePin = 0x00000004;
static constexpr uint32_t kResetCauseSoftware = 0x00000008;
static constexpr uint32_t kResetCauseIndependentWatchdog = 0x00000010;
static constexpr uint32_t kResetCauseWindowWatchdog = 0x00000020;
static constexpr uint32_t kResetCauseCpu = 0x00000040;
static constexpr uint32_t kResetCauseDomain1 = 0x00000080;
static constexpr uint32_t kResetCauseDomain2 = 0x00000100;
static constexpr uint32_t kResetCauseLowPower = 0x00000200;
static constexpr uint32_t kResetCauseUnknown = 0x80000000;
static constexpr uint16_t kCapabilityPayloadLen = 36;
static constexpr uint16_t kCapabilityV1PayloadLen = 36;
static constexpr uint16_t kCapabilityV2PayloadLen = 80;
static constexpr uint16_t kCapabilityV3PayloadLen = 112;
static constexpr uint16_t kCapabilityV4PayloadLen = 192;
static constexpr uint16_t kCapabilityV5PayloadLen = 224;
static constexpr uint16_t kCapabilityV6PayloadLen = 272;
static constexpr uint8_t kCapabilityV2BusDescriptorLen = 20;
static constexpr uint8_t kCapabilityProtocolVersionOffset = 8;
static constexpr uint8_t kCapabilityProfileMajorOffset = 9;
static constexpr uint8_t kCapabilityProfileMinorOffset = 10;
static constexpr uint8_t kCapabilityBusCountOffset = 36;
static constexpr uint8_t kCapabilityBusDescriptorSizeOffset = 37;
static constexpr uint8_t kCapabilityBusDescriptorsOffset = 40;
static constexpr uint8_t kCapabilityBusControlTxAllowedOffset = 6;
static constexpr uint8_t kCapabilitySupportedDownlinkOffset = 84;
static constexpr uint8_t kCapabilityFirmwareProfileOffset = 192;
static constexpr uint8_t kCapabilityHostCommandRxOffset = 195;
static constexpr uint8_t kCapabilityControlPathOffset = 196;
static constexpr uint16_t kAdcSamplePayloadLen = 44;
static constexpr uint8_t kFirmwareGitShaFieldLen = 12;
static constexpr uint8_t kFirmwareEnvNameFieldLen = 48;

}  // namespace csm
